"""Add pending messages queue to dialogs

Revision ID: 07733f217740
Revises: 45d24e71548a
Create Date: 2025-10-21 23:40:46.640111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07733f217740'
down_revision: Union[str, Sequence[str], None] = '45d24e71548a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dialogs', sa.Column('pending_messages', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('dialogs', sa.Column('pending_since', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dialogs', 'pending_since')
    op.drop_column('dialogs', 'pending_messages')
    # ### end Alembic commands ###
