"""Create dialogs table

Revision ID: 333237e50c84
Revises: 
Create Date: 2025-10-21 21:34:54.026814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '333237e50c84'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('current_state', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dialogs_chat_id'), 'dialogs', ['chat_id'], unique=True)
    op.create_index(op.f('ix_dialogs_id'), 'dialogs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dialogs_id'), table_name='dialogs')
    op.drop_index(op.f('ix_dialogs_chat_id'), table_name='dialogs')
    op.drop_table('dialogs')
    # ### end Alembic commands ###
