"""Add history and created_at columns to dialogs

Revision ID: 45d24e71548a
Revises: 333237e50c84
Create Date: 2025-10-21 21:42:53.173682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45d24e71548a'
down_revision: Union[str, Sequence[str], None] = '333237e50c84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dialogs', sa.Column('history', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('dialogs', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dialogs', 'created_at')
    op.drop_column('dialogs', 'history')
    # ### end Alembic commands ###
