"""Add pending messages queue to dialogs000

Revision ID: a1a3b50f9009
Revises: 07733f217740
Create Date: 2025-10-22 12:18:36.886842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1a3b50f9009'
down_revision: Union[str, Sequence[str], None] = '07733f217740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dialogs', sa.Column('deal_id', sa.Integer(), nullable=True))
    op.add_column('dialogs', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.add_column('dialogs', sa.Column('funnel_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_dialogs_deal_id'), 'dialogs', ['deal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dialogs_deal_id'), table_name='dialogs')
    op.drop_column('dialogs', 'funnel_id')
    op.drop_column('dialogs', 'manager_id')
    op.drop_column('dialogs', 'deal_id')
    # ### end Alembic commands ###
